import type { NextPage } from "next";
import Head from "next/head";
import {
  BottomSection,
  FeatureSection,
  HeroSection,
  ReviewSection,
} from "../layouts";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title> Home | Manage</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HeroSection />
      <FeatureSection />
      <ReviewSection />
      <BottomSection />
    </>
  );
};

export default Home;
